/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Campaign {
  'id' : bigint,
  'organizerBio' : string,
  'title' : string,
  'goalAmount' : number,
  'active' : boolean,
  'startAt' : Time,
  'tags' : Array<string>,
  'organizerName' : string,
  'endAt' : Time,
  'imageUrl' : string,
  'shortDescription' : string,
  'category' : string,
  'fullDescription' : string,
  'contributors' : bigint,
  'amountRaised' : number,
}
export interface Donation {
  'id' : bigint,
  'donorName' : string,
  'campaignId' : bigint,
  'timestamp' : Time,
  'amount' : number,
}
export interface FractionalizationSettings {
  'pricePerUnit' : number,
  'totalUnits' : bigint,
  'unitsSold' : bigint,
}
export interface Gift {
  'id' : bigint,
  'campaignId' : bigint,
  'description' : string,
  'timestamp' : Time,
  'itemName' : string,
  'contactEmail' : string,
  'estimatedValue' : number,
}
export type Time = bigint;
export interface UnitClaim {
  'claimantName' : string,
  'campaignId' : bigint,
  'timestamp' : Time,
  'unitsClaimed' : bigint,
}
export interface Volunteer {
  'id' : bigint,
  'campaignId' : bigint,
  'fullName' : string,
  'email' : string,
  'availability' : Array<string>,
  'timestamp' : Time,
  'skills' : string,
}
export interface _SERVICE {
  'allCampaigns' : ActorMethod<[], Array<Campaign>>,
  'claimUnits' : ActorMethod<[bigint, string, bigint], boolean>,
  'createCampaign' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      string,
      string,
      string,
      Time,
      Time,
      Array<string>,
    ],
    Campaign
  >,
  'getActiveCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllFractionalizationSettings' : ActorMethod<
    [],
    Array<[bigint, FractionalizationSettings]>
  >,
  'getCampaign' : ActorMethod<[bigint], [] | [Campaign]>,
  'getCampaignsByCategory' : ActorMethod<[string], Array<Campaign>>,
  'getDonationsByCampaign' : ActorMethod<[bigint], Array<Donation>>,
  'getFractionalizationSettings' : ActorMethod<
    [bigint],
    [] | [FractionalizationSettings]
  >,
  'getGiftsByCampaign' : ActorMethod<[bigint], Array<Gift>>,
  'getUnitClaims' : ActorMethod<[bigint], Array<UnitClaim>>,
  'getVolunteersByCampaign' : ActorMethod<[bigint], Array<Volunteer>>,
  'recordDonation' : ActorMethod<[bigint, number, string], [] | [Campaign]>,
  'recordGift' : ActorMethod<[bigint, string, number, string, string], boolean>,
  'registerVolunteer' : ActorMethod<
    [bigint, string, string, Array<string>, string],
    boolean
  >,
  'setFractionalizationSettings' : ActorMethod<
    [bigint, bigint, number],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];