/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Campaign {
  'id' : bigint,
  'organizerBio' : string,
  'title' : string,
  'goalAmount' : number,
  'active' : boolean,
  'startAt' : string,
  'tags' : Array<string>,
  'organizerName' : string,
  'endAt' : string,
  'imageUrl' : string,
  'shortDescription' : string,
  'category' : string,
  'fullDescription' : string,
  'contributors' : bigint,
  'amountRaised' : number,
}
export interface _SERVICE {
  'allCampaigns' : ActorMethod<[], Array<Campaign>>,
  'createCampaign' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
    ],
    Campaign
  >,
  'getCampaign' : ActorMethod<[bigint], [] | [Campaign]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];