/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'organizerBio' : IDL.Text,
  'title' : IDL.Text,
  'goalAmount' : IDL.Float64,
  'active' : IDL.Bool,
  'startAt' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'organizerName' : IDL.Text,
  'endAt' : IDL.Text,
  'imageUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
  'category' : IDL.Text,
  'fullDescription' : IDL.Text,
  'contributors' : IDL.Nat,
  'amountRaised' : IDL.Float64,
});

export const idlService = IDL.Service({
  'allCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'createCampaign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [Campaign],
      [],
    ),
  'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(Campaign)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'organizerBio' : IDL.Text,
    'title' : IDL.Text,
    'goalAmount' : IDL.Float64,
    'active' : IDL.Bool,
    'startAt' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'organizerName' : IDL.Text,
    'endAt' : IDL.Text,
    'imageUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
    'category' : IDL.Text,
    'fullDescription' : IDL.Text,
    'contributors' : IDL.Nat,
    'amountRaised' : IDL.Float64,
  });
  
  return IDL.Service({
    'allCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'createCampaign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [Campaign],
        [],
      ),
    'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(Campaign)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };