/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FractionalizationSettings {
    pricePerUnit: number;
    totalUnits: bigint;
    unitsSold: bigint;
}
export type Time = bigint;
export interface Donation {
    id: bigint;
    donorName: string;
    campaignId: bigint;
    timestamp: Time;
    amount: number;
}
export interface Campaign {
    id: bigint;
    organizerBio: string;
    title: string;
    goalAmount: number;
    active: boolean;
    startAt: Time;
    tags: Array<string>;
    organizerName: string;
    endAt: Time;
    imageUrl: string;
    shortDescription: string;
    category: string;
    fullDescription: string;
    contributors: bigint;
    amountRaised: number;
}
export interface Gift {
    id: bigint;
    campaignId: bigint;
    description: string;
    timestamp: Time;
    itemName: string;
    contactEmail: string;
    estimatedValue: number;
}
export interface UnitClaim {
    claimantName: string;
    campaignId: bigint;
    timestamp: Time;
    unitsClaimed: bigint;
}
export interface Volunteer {
    id: bigint;
    campaignId: bigint;
    fullName: string;
    email: string;
    availability: Array<string>;
    timestamp: Time;
    skills: string;
}
export interface backendInterface {
    allCampaigns(): Promise<Array<Campaign>>;
    claimUnits(campaignId: bigint, claimantName: string, units: bigint): Promise<boolean>;
    createCampaign(title: string, shortDescription: string, fullDescription: string, category: string, goalAmount: number, organizerName: string, organizerBio: string, imageUrl: string, startAt: Time, endAt: Time, tags: Array<string>): Promise<Campaign>;
    getActiveCampaigns(): Promise<Array<Campaign>>;
    getAllFractionalizationSettings(): Promise<Array<[bigint, FractionalizationSettings]>>;
    getCampaign(id: bigint): Promise<Campaign | null>;
    getCampaignsByCategory(category: string): Promise<Array<Campaign>>;
    getDonationsByCampaign(campaignId: bigint): Promise<Array<Donation>>;
    getFractionalizationSettings(campaignId: bigint): Promise<FractionalizationSettings | null>;
    getGiftsByCampaign(campaignId: bigint): Promise<Array<Gift>>;
    getUnitClaims(campaignId: bigint): Promise<Array<UnitClaim>>;
    getVolunteersByCampaign(campaignId: bigint): Promise<Array<Volunteer>>;
    recordDonation(campaignId: bigint, amount: number, donorName: string): Promise<Campaign | null>;
    recordGift(campaignId: bigint, itemName: string, estimatedValue: number, description: string, contactEmail: string): Promise<boolean>;
    registerVolunteer(campaignId: bigint, fullName: string, email: string, availability: Array<string>, skills: string): Promise<boolean>;
    setFractionalizationSettings(campaignId: bigint, totalUnits: bigint, pricePerUnit: number): Promise<boolean>;
}
import type { Campaign as _Campaign, FractionalizationSettings as _FractionalizationSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async allCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.allCampaigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allCampaigns();
            return result;
        }
    }
    async claimUnits(arg0: bigint, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimUnits(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimUnits(arg0, arg1, arg2);
            return result;
        }
    }
    async createCampaign(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: string, arg6: string, arg7: string, arg8: Time, arg9: Time, arg10: Array<string>): Promise<Campaign> {
        if (this.processError) {
            try {
                const result = await this.actor.createCampaign(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCampaign(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async getActiveCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCampaigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCampaigns();
            return result;
        }
    }
    async getAllFractionalizationSettings(): Promise<Array<[bigint, FractionalizationSettings]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFractionalizationSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFractionalizationSettings();
            return result;
        }
    }
    async getCampaign(arg0: bigint): Promise<Campaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaign(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaign(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaignsByCategory(arg0: string): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaignsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaignsByCategory(arg0);
            return result;
        }
    }
    async getDonationsByCampaign(arg0: bigint): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsByCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsByCampaign(arg0);
            return result;
        }
    }
    async getFractionalizationSettings(arg0: bigint): Promise<FractionalizationSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFractionalizationSettings(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFractionalizationSettings(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGiftsByCampaign(arg0: bigint): Promise<Array<Gift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftsByCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftsByCampaign(arg0);
            return result;
        }
    }
    async getUnitClaims(arg0: bigint): Promise<Array<UnitClaim>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnitClaims(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnitClaims(arg0);
            return result;
        }
    }
    async getVolunteersByCampaign(arg0: bigint): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteersByCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteersByCampaign(arg0);
            return result;
        }
    }
    async recordDonation(arg0: bigint, arg1: number, arg2: string): Promise<Campaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDonation(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDonation(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordGift(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGift(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGift(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async registerVolunteer(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVolunteer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVolunteer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async setFractionalizationSettings(arg0: bigint, arg1: bigint, arg2: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setFractionalizationSettings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFractionalizationSettings(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Campaign]): Campaign | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FractionalizationSettings]): FractionalizationSettings | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
